### PR TITLE
[BCP-003-002] JSON Web Token Claim Values

### PR DESCRIPTION
**Pull request by dannymeloy**
So I thought I'd add an initial draft of what the contents of a JSON Web Token _might_ look like for use with the IS-10 Authorization process. This is a very rough first draft so feel free to pull it to pieces. Please find a JSON schema and a JSON example in this PR.

There are a multitude of factors to consider when tackling this issue, which ultimately revolves around trying to balance the following aspects:
- Network overhead - Do we want the tokens to be self-signed and self-contained? Thus meaning the resource server can validate the JWT itself, rather than having to hand off the validation process to the Authorization Server? This would likely mean more verbose tokens but with less network chatter. It also moves the validation process to the Resource Server instead of the Auth Server. That might be a bad thing?
- Size and complexity of tokens - These tokens ultimately have to live within the HTTP Authorization Header (most servers implement an 8KB restriction) so they can't be too large. Also these tokens will likely be passed with every HTTP request in the network, so keeping the size lower is beneficial. Also, with larger, more complex tokens comes with it the requirement of increased processing - obviously with some hardware-based devices, processing power might be limited. 
- Population of claims - the granularity is also an issue. Can a token be used against multiple APIs or is it a 1-to-1 mapping between API and token? I'd argue for the sake of simplicity, that a token can be used against multiple NMOS APIs (as most OAuth providers allow tokens with many scopes.) If the `aud` claim is populated with specific nodes/devices, then a new token will likely need to be requested with every API interaction, but the scopes would be nice and granular. Or are tokens requested initially without knowledge of specific nodes/devices, in which case the `aud` claim could be populated with wild card characters, making them more universal? I've assumed wild carding is permissible in my examples.

That's a bit of a stream of consciousness, but food for thought.

### CODE REVIEW

**Comment by andrewbonney** [comment]
A few general comments on the sample token first:

- We may not need to include 'scope' in the token itself as it's duplicated by the 'x-nmos-api' claim.
- An access type of 'none' could be handled by simply omitting a given spec from the token, although I do see how it adds clarity if one of the requested scopes has no assigned permission. Perhaps if 'scope' is omitted this is more important.
- Unless there's a specific use case in mind, 'versions' may be unnecessary.
- It might be worth broadening the 'is-XX' token in case future specs use a different pattern. We should probably be less restrictive here, but have strong definitions for each spec somewhere like the parameter registers.

Beyond that, the use of wildcards in 'aud' seems really useful, as long as we use a DNS name or similar in 'aud' rather than Node IDs. This could allow DNS names like 'node1.studio1.mydomain.com' and 'node2.studio1.mydomain.com' to use the wildcard of '*.studio1.mydomain.com'. The Node would of course either need to know its fully qualified domain name, or have reverse DNS available on the network to resolve multiple potential aliases.

We could take that a little further if we really want to keep the token size down in the most complex cases (for example where a Node is shared between multiple groupings). For example, if 'aud' could relate to DNS PTRs as well you could do similar stuff to what the DNS-SD spec does and use DNS to create truly flexible groupings without having to define a new grouping mechanism. For example a PTR of 'studio1.mydomain.com' could link to as many specific A records as you wish, with validity linked to the DNS record's TTL. The resource server would of course have to check it was still part of that group each time the TTL expired. There are of course questions over DNS security here too, but there are solutions to that which don't require new invention.

For the claims, I think it's important that BCP-003-02 itself is kept as simple as possible, but attempts to allow for future extensibility which might be required by the individual IS specs. For example, we might define 'read' and 'write' access types here which (unless otherwise specified) mean you can either do all GET/HEAD/OPTIONS etc or all PUT/PATCH/DELETE etc. An individual IS (and version) may wish to override this in the parameter registers, for example in the case of IS-04's Query API you may want 'read' to also allow POSTs to '/subscriptions' as this is a form of read operation (alternative solution to this at the bottom...).

Individual IS's could then choose to define further 'access' types as they wish for a given specification version. For example a future spec may wish to allow resources to be updated but not created or deleted, requiring an 'update' access type. Or similarly a 'lock' or 'unlock' access (or perhaps action?) type.

We should also consider whether the claims should allow us to sub-divide API instances. In some cases Nodes may be very large, but a user may only be permitted to modify certain Senders or audio channel Outputs for example. In this case you may want a token that allows an array of permitted resources to be specified (again this could be done on a per-spec level):
```
"x-nmos-api": {
  "is-05": {
    "update": {
      "resources": ["senders.2d2ed05a-4b2e-4cc9-8e8c-cc62a27db97a"]
    }
  }
}
```
```
"x-nmos-api": {
  "is-08": {
    "update": {
      "resources": ["outputs.MyOutput"]
    }
  }
}
```
This could also be used for specs which include multiple API definitions, for example:
```
"x-nmos-api": {
  "is-04": {
    "write": {
      "resources": ["registration.*", "query.subscriptions"]
    },
    "read": {
      "resources": ["node.*", "query.*"]
    }
  }
}
```

More food for thought...

**Comment by peterbrightwell** [comment]
As @andrewbonney says, we may not need 'scope' in the token... don't include that until we are sure that we do.

Also, consider whether there is an alternative to using "is-04" and "is-05". Apart from in the system API (which has "is04", based on what went into TR-1001) we don't use these AMWA spec identifiers within API messages themselves. And IS-04 includes multiple APIs. Andrew's fourth bullet is probably related to this.

**Comment by garethsb-sony** [comment]
> Also, consider whether there is an alternative to using "is-04" and "is-05". Apart from in the system API (which has "is04", based on what went into TR-1001) 

True. Using the API slugs could work ('registration', 'query', 'node', 'events', ...), with or without the 'x-nmos/' prefix.

**Comment by dannymeloy** [comment]
I think it should be noted that a "new" OAuth2 grant flow has been ratified this month, the [Device Authorization Grant](https://tools.ietf.org/html/rfc8628). Whilst not applicable to the majority of NMOS Nodes, it could be considered for hardware-limited or headless devices.

**Comment by NEOAdvancedTechnology** [comment]
To solve the Access Token granularity vs. size issue, I think we need to think in more solid terms about what our practical expectations for real-world deployments and security requirements.

In my thinking, likely a Production Control Room's Broadcast Controller server will be having nearly full control over a coherent production (even if different users of the Broadcast Controller have limited role-based authorized capabilities).  That coherent production (say a specific TV show) may have its owns specific Authorization Server as well.

Then at a higher level, a Network Center's Broadcast Controller may move produced flows between multiple coherent productions, but would not likely be interfering with the production itself, and again it may have its own Authorization Server.

This would imply that the typical Access Token should likely provide authorization to a wide range of equipment within a specific authorization domain.  That equipment may be virtually linked to a particular domain on demand of course (think a video switcher in the equipment room that can become part of any production domain when needed).

BTW the granularity issue is has by people outside our industry, for example see: https://www.pingidentity.com/en/company/blog/posts/2019/oauth2-access-token-multiple-resources-usage-strategies.html

**Comment by NEOAdvancedTechnology** [comment]
This issue will be addressed in IS-10

**Pull request closed without merging**
